# Generated by Django 3.0.4 on 2020-03-12 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('brand', models.CharField(choices=[('Intel', 'Intel'), ('AMD', 'AMD'), ('Qualcomm', 'Qualcomm'), ('Samsung', 'Samsung'), ('Huawei', 'Huawei')], max_length=100)),
                ('performance', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('tdp', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('core_number', models.PositiveIntegerField(blank=True, null=True)),
                ('lithography', models.PositiveIntegerField(blank=True, null=True)),
                ('hyperthreading', models.BooleanField(blank=True, null=True)),
                ('release_date', models.CharField(blank=True, max_length=100, null=True)),
                ('gpu', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MiniPC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('CHUWI', 'Chuwi'), ('PRETECH', 'Pretech'), ('ILIFE', 'iLife'), ('TOPJOY', 'TopJoy'), ('GPD', 'GPD'), ('CUBE', 'Cube'), ('ACER', 'Acer'), ('ASUS', 'Asus'), ('MICROSOFT', 'Microsoft'), ('WEIBU', 'Weibu'), ('ONE', 'One'), ('MAG', 'Mag'), ('XIAOMI', 'Xiaomi')], max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('release_date', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media')),
                ('mean_price', models.PositiveIntegerField(blank=True, null=True)),
                ('min_price', models.PositiveIntegerField(blank=True, null=True)),
                ('weight', models.PositiveIntegerField(blank=True, null=True)),
                ('width', models.CharField(blank=True, max_length=100, null=True)),
                ('length', models.CharField(blank=True, max_length=100, null=True)),
                ('height', models.CharField(blank=True, max_length=100, null=True)),
                ('os', models.CharField(blank=True, max_length=100, null=True)),
                ('storage', models.CharField(blank=True, max_length=100, null=True)),
                ('ram', models.CharField(blank=True, max_length=100, null=True)),
                ('screen_resolution', models.CharField(blank=True, max_length=100, null=True)),
                ('screen_size', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('screen_technology', models.CharField(blank=True, choices=[('IPS', 'IPS'), ('TN', 'TN'), ('VA', 'VA'), ('MVA', 'MVA'), ('OLED', 'OLED')], max_length=20, null=True)),
                ('input_devices', models.CharField(blank=True, max_length=100, null=True)),
                ('battery', models.PositiveIntegerField(blank=True, null=True)),
                ('fingerprint_sensor', models.BooleanField(blank=True, null=True)),
                ('tablet_hinge', models.BooleanField(blank=True, null=True)),
                ('touchscreen', models.BooleanField(blank=True, null=True)),
                ('lit_keyboard', models.BooleanField(blank=True, null=True)),
                ('usb2', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('usb3', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('usbC', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('mini_hdmi', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('micro_hdmi', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('microsd_slot', models.BooleanField(blank=True, null=True)),
                ('sd_slot', models.BooleanField(blank=True, null=True)),
                ('bluetooth_version', models.CharField(blank=True, max_length=100, null=True)),
                ('cpu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.CPU')),
            ],
        ),
    ]
