# Generated by Django 3.0.4 on 2020-03-12 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_minipc_length_m2_nvme_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='media/media'),
        ),
        migrations.AlterField(
            model_name='minipc',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/media'),
        ),
    ]
