# Generated by Django 3.0.4 on 2020-03-13 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20200312_2355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='minipc',
            old_name='mean_price',
            new_name='recommended_price',
        ),
        migrations.AddField(
            model_name='minipc',
            name='alias',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='minipc',
            name='battery_wattage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='minipc',
            name='input_devices',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Touchpad', 'Touchpad'), ('Trackpoint', 'Trackpoint'), ('Optical Touch Sensor', 'Optical Touch Sensor'), ('Touchpad + Gamepad', 'Touchpad + Gamepad'), ('Gamepad', 'Gamepad')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='minipc',
            name='length_m2_nvme_port',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='minipc',
            name='length_m2_sata_port',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='minipc',
            name='m2_nvme_port',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='minipc',
            name='m2_sata_port',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
