# Generated by Django 3.0.4 on 2020-03-12 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BRAND',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('CHUWI', 'Chuwi'), ('PRETECH', 'Pretech'), ('ILIFE', 'iLife'), ('TOPJOY', 'TopJoy'), ('GPD', 'GPD'), ('CUBE', 'Cube'), ('ACER', 'Acer'), ('ASUS', 'Asus'), ('MICROSOFT', 'Microsoft'), ('WEIBU', 'Weibu'), ('ONE', 'One'), ('MAG', 'Mag'), ('XIAOMI', 'Xiaomi')], max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='media')),
            ],
        ),
        migrations.AlterField(
            model_name='minipc',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.BRAND'),
        ),
    ]
