# Generated by Django 3.0.4 on 2020-03-12 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200312_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minipc',
            name='m2_slot_nvme',
        ),
        migrations.RemoveField(
            model_name='minipc',
            name='m2_slot_sata',
        ),
        migrations.RemoveField(
            model_name='minipc',
            name='optical_sensor',
        ),
        migrations.RemoveField(
            model_name='minipc',
            name='screen_resolution',
        ),
        migrations.RemoveField(
            model_name='minipc',
            name='touchpad',
        ),
        migrations.RemoveField(
            model_name='minipc',
            name='trackpoint',
        ),
        migrations.AddField(
            model_name='brand',
            name='logo_source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cpu',
            name='gpu_performance',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='minipc',
            name='battery_voltage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='minipc',
            name='battery_wattage',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='minipc',
            name='image_source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='minipc',
            name='jack',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='minipc',
            name='screen_resolution_x',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='minipc',
            name='screen_resolution_y',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='minipc',
            name='storage_expansion',
            field=models.CharField(blank=True, choices=[('M.2 2242 SATA', 'M.2 2242 SATA'), ('M.2 2280 SATA', 'M.2 2280 SATA'), ('M.2 2242 NVMe', 'M.2 2242 NVMe'), ('M.2 2280 NVMe', 'M.2 2280 NVMe'), ('No', 'No')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='minipc',
            name='stylus_compatibility',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='minipc',
            name='wifi_version',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='minipc',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='minipc',
            name='input_devices',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Touchpad', 'Touchpad'), ('Trackpoint', 'Trackpoint'), ('Optical Touch Sensor', 'Optical Touch Sensor'), ('Touchpad + Gamepad', 'Touchpad + Gamepad')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='minipc',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='minipc',
            name='screen_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='minipc',
            name='tablet_hinge',
            field=models.CharField(blank=True, choices=[('360-degree', '360-degree'), ('Laptopt-like hinge', 'Laptop-like hinge')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='minipc',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
