# Generated by Django 3.0.4 on 2020-03-12 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200312_1907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='minipc',
            old_name='ram_capacity',
            new_name='ram_max_capacity',
        ),
        migrations.RemoveField(
            model_name='minipc',
            name='storage_expansion',
        ),
        migrations.AddField(
            model_name='minipc',
            name='hdmi',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='minipc',
            name='length_m2_sata_port',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='minipc',
            name='m2_nvme_port',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='minipc',
            name='m2_sata_port',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='minipc',
            name='ram_min_capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='minipc',
            name='thunderbolt',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='gpu_performance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='performance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
