# Generated by Django 3.0.4 on 2020-03-12 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200312_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(choices=[('Chuwi', 'Chuwi'), ('Pretech', 'Pretech'), ('iLife', 'iLife'), ('TopJoy', 'TopJoy'), ('GPD', 'GPD'), ('Cube', 'Cube'), ('Acer', 'Acer'), ('Asus', 'Asus'), ('Microsoft', 'Microsoft'), ('Weibu', 'Weibu'), ('One', 'One'), ('Mag', 'Mag'), ('Xiami', 'Xiaomi'), ('Samsung', 'Samsung'), ('Peakago', 'Peakago')], max_length=100),
        ),
    ]
